### PR TITLE
Add support for multi-file import

### PR DESCRIPTION
**Pull request by hyrodium**
This PR enables multi-file import for PCD files.
I have edited the script with reference to the PLY file import script from:
https://github.com/blender/blender-addons/blob/016430de4b06714c006bb6de2ae3a28e05a86169/io_mesh_ply/__init__.py#L47-L84

### CODE REVIEW

**Review by MarkHedleyJones — CHANGES_REQUESTED** [review]
Awesome, thank you very much for your contribution :+1: 
Could you please increment the version number contained in [io_pcd/__init__.py](https://github.com/MarkHedleyJones/blender-pcd-io/blob/25114246c94387e5cc91f1e50ae5c85cfd94c41f/io_pcd/__init__.py) to `1.4.0`.

Like so:

    "version": (1, 4, 0),

**Review by MarkHedleyJones — APPROVED** [review]
Looks good to me

**Comment by MarkHedleyJones** [comment]
@hyrodium Thanks for that!

**Comment by hyrodium** [comment]
@MarkHedleyJones Could you tag and release `v1.5.0`?

**Comment by MarkHedleyJones** [comment]
Done, sorry about that.

**Comment by hyrodium** [comment]
Thank you!

**Pull request merged**
